/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeondisplay;

import java.awt.GridLayout;
import java.awt.event.MouseWheelEvent;
import static java.lang.Math.max;
import static java.lang.Math.min;

/**
 *
 * @author plis
 */
public class MiscMenu extends javax.swing.JPanel {

    /**
     * Creates new form MiscMenu
     */
    
    DungeonDisplay parentDD;
    public MiscMenu(DungeonDisplay parent) {
        parentDD = parent;
        initComponents();
    }
    
    static int roomNum = 0;
    
    public static int getRoomNum()
    {
        return roomNum;
    }
    public void changeHideAllButton()
    {
        HideAllRoomsButtonActionPerformed(null);
    }
    
    // zoom 20%. negative rot = zoom in, positive rot = zoom out
    public void resize(int rot) {
        resizeSlider.setValue((resizeSlider.getValue() * (10 + (rot > 0 ? -2 : 2))) / 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roomNumberSpinner = new javax.swing.JSpinner();
        HideAllRoomsButton = new javax.swing.JButton();
        hideRoomButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resizeSpinner = new javax.swing.JSpinner();
        resizeSlider = new javax.swing.JSlider();

        setPreferredSize(new java.awt.Dimension(200, 800));

        roomNumberSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 32767, 1));
        roomNumberSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                roomNumberSpinnerStateChanged(evt);
            }
        });

        HideAllRoomsButton.setText("Hide All Rooms");
        HideAllRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HideAllRoomsButtonActionPerformed(evt);
            }
        });

        hideRoomButton.setText("Hide Squares");
        hideRoomButton.setMargin(new java.awt.Insets(2, 12, 2, 12));
        hideRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideRoomButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Room #");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setLabelFor(resizeSlider);
        jLabel2.setText("Resize Tiles");

        jLabel3.setText("(Very Buggy)");

        resizeSpinner.setValue(80);
        resizeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resizeSpinnerStateChanged(evt);
            }
        });

        resizeSlider.setMaximum(160);
        resizeSlider.setMinimum(10);
        resizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resizeSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(resizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(resizeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(resizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(HideAllRoomsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hideRoomButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(roomNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roomNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(hideRoomButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addComponent(HideAllRoomsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 543, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HideAllRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HideAllRoomsButtonActionPerformed
        // TODO add your handling code here:
        if(HideAllRoomsButton.getText().equals("Hide All Rooms"))
        {
            HideAllRoomsButton.setText("Show All Rooms");
            ImagePane.hide = true;
        }
        else if(HideAllRoomsButton.getText().equals("Show All Rooms"))
        {
            HideAllRoomsButton.setText("Hide All Rooms");
            ImagePane.hide = false;
        }
        parentDD.displayPanel.repaint();
    }//GEN-LAST:event_HideAllRoomsButtonActionPerformed

    private void roomNumberSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_roomNumberSpinnerStateChanged
        // TODO add your handling code here:
        roomNum = (Integer)roomNumberSpinner.getValue();
        ImagePane.writeType = 5;
    }//GEN-LAST:event_roomNumberSpinnerStateChanged

    private void hideRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideRoomButtonActionPerformed
        // TODO add your handling code here:
        ImagePane.writeType = 5;
        
    }//GEN-LAST:event_hideRoomButtonActionPerformed

    private void resizeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resizeSpinnerStateChanged
        // TODO add your handling code here:
        int value = (Integer) resizeSpinner.getValue();
        if(value < resizeSlider.getMinimum() || value > resizeSlider.getMaximum())
        {
            value = max(value, resizeSlider.getMinimum());
            value = min(value, resizeSlider.getMaximum());
            resizeSpinner.setValue(value);
        }
            
        resizeSlider.setValue(value);
        
        parentDD.displayPanel.fullsquaresize = value;
        parentDD.displayPanel.revalidate();
        parentDD.displayPanel.repaint();
        
    }//GEN-LAST:event_resizeSpinnerStateChanged

    private void resizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resizeSliderStateChanged
        // TODO add your handling code here:
        resizeSpinner.setValue((Integer)resizeSlider.getValue());
        
    }//GEN-LAST:event_resizeSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HideAllRoomsButton;
    private javax.swing.JButton hideRoomButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider resizeSlider;
    private javax.swing.JSpinner resizeSpinner;
    private javax.swing.JSpinner roomNumberSpinner;
    // End of variables declaration//GEN-END:variables
}
